---
- hosts: all
  become: yes
# Install and configure GitLab Community Edition
  tasks:
  - name: install gitlab-ce
    include_tasks: gitlab-ce.yml

# Create a Website in Nginx if it is installed
#  - name: Check if Nginx is installed
#    ansible.builtin.stat:
#      path: /etc/nginx
#     register: nginx
#  - name: install nginx
#    include_tasks: nginx.yml
#   when: nginx.stat.exists
